/* Access SQL export data follows. Auto-generated. */

/* Tables */
DROP TABLE [AZIENDE] /**WEAK**/;
CREATE TABLE [AZIENDE] (
[CodInt] INTEGER NOT NULL,
[CodCon] INTEGER,
[Tipo] INTEGER,
[CodAux] INTEGER,
[CodFis] TEXT(16),
[ParIVA] TEXT(11),
[Nome] LONGTEXT,
[Note] LONGTEXT,
[FirstContact] DATETIME
);
CREATE UNIQUE INDEX [PrimaryKey] ON [AZIENDE] ([CodInt] ASC) WITH PRIMARY DISALLOW NULL;

DROP TABLE [CONNESSI] /**WEAK**/;
CREATE TABLE [CONNESSI] (
[CodCos] INTEGER NOT NULL,
[CodCon] INTEGER,
[Tipo] INTEGER,
[Data] DATETIME,
[Contenuto] TEXT(50),
[Note] LONGTEXT,
[URL] LONGTEXT
);
CREATE UNIQUE INDEX [PrimaryKey] ON [CONNESSI] ([CodCos] ASC) WITH PRIMARY DISALLOW NULL;
CREATE INDEX [CONNESSICodCon] ON [CONNESSI] ([CodCon] ASC);

DROP TABLE [CONTAT] /**WEAK**/;
CREATE TABLE [CONTAT] (
[CodCon] INTEGER NOT NULL,
[Tipo] INTEGER,
[Nome_Tit] TEXT(10),
[Nome_Pre1] TEXT(20),
[Nome_Pre2] TEXT(40),
[Nome_Main] TEXT(40),
[Nome_Suf] TEXT(10),
[Classe] TEXT(15),
[Settore] TEXT(35),
[Note] LONGTEXT
);
CREATE UNIQUE INDEX [PrimaryKey] ON [CONTAT] ([CodCon] ASC) WITH PRIMARY DISALLOW NULL;

DROP TABLE [DATEIMPO] /**WEAK**/;
CREATE TABLE [DATEIMPO] (
[Prog] COUNTER NOT NULL,
[CodCon] INTEGER,
[Tipo] INTEGER,
[Data] DATETIME,
[Nota] TEXT(50)
);
CREATE UNIQUE INDEX [PrimaryKey] ON [DATEIMPO] ([Prog] ASC) WITH PRIMARY DISALLOW NULL;

DROP TABLE [GRUPPI] /**WEAK**/;
CREATE TABLE [GRUPPI] (
[CodGrp] INTEGER NOT NULL,
[Desc] TEXT(30)
);
CREATE UNIQUE INDEX [PrimaryKey] ON [GRUPPI] ([CodGrp] ASC) WITH PRIMARY DISALLOW NULL;

DROP TABLE [INDIRIZ] /**WEAK**/;
CREATE TABLE [INDIRIZ] (
[CodInd] INTEGER NOT NULL,
[CodCon] INTEGER,
[Tipo] INTEGER,
[Indirizzo] LONGTEXT,
[Note] TEXT(40)
);
CREATE UNIQUE INDEX [PrimaryKey] ON [INDIRIZ] ([CodInd] ASC) WITH PRIMARY DISALLOW NULL;

DROP TABLE [INGRUPPO] /**WEAK**/;
CREATE TABLE [INGRUPPO] (
[Prog] COUNTER NOT NULL,
[CodCon] INTEGER,
[CodGrp] INTEGER
);
CREATE UNIQUE INDEX [PrimaryKey] ON [INGRUPPO] ([Prog] ASC) WITH PRIMARY DISALLOW NULL;
CREATE INDEX [INGRUPPOCodCon] ON [INGRUPPO] ([CodCon] ASC);

DROP TABLE [NICKNAME] /**WEAK**/;
CREATE TABLE [NICKNAME] (
[Prog] COUNTER NOT NULL,
[CodCon] INTEGER,
[NickName] TEXT(40)
);
CREATE UNIQUE INDEX [PrimaryKey] ON [NICKNAME] ([Prog] ASC) WITH PRIMARY DISALLOW NULL;

DROP TABLE [REFERENT] /**WEAK**/;
CREATE TABLE [REFERENT] (
[Prog] COUNTER NOT NULL,
[CodCon] INTEGER,
[CodRef] INTEGER
);
CREATE UNIQUE INDEX [PrimaryKey] ON [REFERENT] ([Prog] ASC) WITH PRIMARY DISALLOW NULL;

DROP TABLE [TELEF] /**WEAK**/;
CREATE TABLE [TELEF] (
[CodTel] INTEGER NOT NULL,
[CodCon] INTEGER,
[Tipo] INTEGER,
[Tel_Pre1] TEXT(6),
[Tel_Pre2] TEXT(6),
[Telefono] TEXT(18),
[Note] TEXT(40)
);
CREATE UNIQUE INDEX [PrimaryKey] ON [TELEF] ([CodTel] ASC) WITH PRIMARY DISALLOW NULL;

/* Relations */
/* Foreign keys for AZIENDE */
ALTER TABLE [AZIENDE] ADD CONSTRAINT [CONTATAZIENDE] FOREIGN KEY (CodCon) REFERENCES [CONTAT] (CodCon);

/* Foreign keys for CONNESSI */
ALTER TABLE [CONNESSI] ADD CONSTRAINT [CONTATCONNESSI] FOREIGN KEY (CodCon) REFERENCES [CONTAT] (CodCon);

/* Foreign keys for DATEIMPO */
ALTER TABLE [DATEIMPO] ADD CONSTRAINT [CONTATDATEIMPO] FOREIGN KEY (CodCon) REFERENCES [CONTAT] (CodCon);

/* Foreign keys for INDIRIZ */
ALTER TABLE [INDIRIZ] ADD CONSTRAINT [CONTATINDIRIZ] FOREIGN KEY (CodCon) REFERENCES [CONTAT] (CodCon);

/* Foreign keys for INGRUPPO */
ALTER TABLE [INGRUPPO] ADD CONSTRAINT [CONTATINGRUPPO] FOREIGN KEY (CodCon) REFERENCES [CONTAT] (CodCon);
ALTER TABLE [INGRUPPO] ADD CONSTRAINT [GRUPPIINGRUPPO] FOREIGN KEY (CodGrp) REFERENCES [GRUPPI] (CodGrp);

/* Foreign keys for NICKNAME */
ALTER TABLE [NICKNAME] ADD CONSTRAINT [CONTATNICKNAME] FOREIGN KEY (CodCon) REFERENCES [CONTAT] (CodCon);

/* Foreign keys for REFERENT */
ALTER TABLE [REFERENT] ADD CONSTRAINT [CONTATREFERENT] FOREIGN KEY (CodCon) REFERENCES [CONTAT] (CodCon);

/* Foreign keys for TELEF */
ALTER TABLE [TELEF] ADD CONSTRAINT [CONTATTELEF] FOREIGN KEY (CodCon) REFERENCES [CONTAT] (CodCon);

/* Views */
/* Procedures */
/* Table data */
/* Data for table AZIENDE */

/* Data for table CONNESSI */

/* Data for table CONTAT */

/* Data for table DATEIMPO */

/* Data for table GRUPPI */

/* Data for table INDIRIZ */

/* Data for table INGRUPPO */

/* Data for table NICKNAME */

/* Data for table REFERENT */

/* Data for table TELEF */

/* Access SQL export data end. */
