<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <link rel="icon" href="./res/siteicon.gif" />
    <link rel="stylesheet" type="text/css" href="./res/main.css" />
    <title>Pasticceria Jones</title>
    <meta http-equiv="Pragma" content="no-cache">
    <meta http-equiv="Cache-Control" content="no-cache">
    <meta http-equiv="Cache-Control" content="must-revalidate">
    <meta http-equiv="expires" content="0">
<%
  Response.Expires = 0;
%>
  </head>
